language: python
python:
- '3.6'
os:
- linux
env:
  global:
  - TX_BRANCH="master"
install:
- pip install --upgrade pip setuptools wheel
- pip install transifex-client sphinx sphinx-intl
- pip install -r requísitos.txt
- pip install coveralls codecov
- python setup.py sdist bdist_wheel
- pip install tikon --no-index --find-links=./dist
script:
- cd pruebas
- coverage run -m unittest
after_success:
- coveralls --rcfile=.coveragerc
- codecov
- cd ..
- cd docs
- if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then sh .tx/tx.sh push; sh .tx/tx.sh pull;
  fi
- cd ..
deploy:
  provider: pypi
  user: julien.malard
  password:
    secure: vvGvuWuf/SfRP9qo+gdyMXuxcvgnC4JIiaOctnCEJWpDy3kxWVCSh6pECYHilkuyVdI26Q0b+VQPmWKPo0vgxofQeEtDvH2npVOuMIW74hOHB3xgIWXXcfsc1fO/adD+S9OS4d7N/7OZQcjn02Bj4FxvdeFk23WrcbHxAIFFWzJoC+EMCvAG9CkzSLvvY6Cf7rwJvL5TtxcqKK5mkWtwMHUIyADJgqFPJBP7+phE/xJJtWRi61AVStfK0GZicigUgaC5z5YSztKL5EUzszpjluM/0oh6P89U69qm2w0VCov3kZvFIVbtoMe74X3UcwrgU43kh+FGmoD5uXKlVAXHzKUjiEG/C9ELfCDzw+YxKhS6gAfnhd1KhkcJVoWfYcZveB2kFaDbAHdlAIvvRtwZ5mFLYkrcZsglLYns0dU0SAiLkoJh67D+gEBzqtfBsrEFt/JwnTFUDWoKNsYxxGMlu9qTV/zki0msKB8X//0NyHEZtwxTDBZjOh4QIYZfu319P2SSKkJGaJDoZwct5XbdUyB3a2w+JoPMWKzzzJfI5RtltvCW00WwpHot7YzVQC6oCJ34tckArYiUbg13aqdJ3w22128uC9BrNcZ12WiEzj5NwJpDmXRnp5MjDBcBWoviSOEdUKKzSnWnE6ytHafG01+iRjYFmwWNrGR7d8tlUuM=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
