language: python
python:
- '3.6'
os:
- linux
env:
  global:
  - TX_BRANCH="master"
install:
- pip install --upgrade pip setuptools wheel
- pip install transifex-client sphinx sphinx-intl
- pip install -r requísitos.txt
- pip install coveralls codecov
- python setup.py sdist bdist_wheel
- pip install tikon --no-index --find-links=./dist
script:
- cd pruebas
- coverage run -m unittest
after_success:
- coveralls --rcfile=.coveragerc
- codecov
- cd ..
- cd docs
- if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then sh .tx/tx.sh push; sh .tx/tx.sh pull;
  fi
- cd ..
deploy:
  provider: pypi
  user: julien.malard
  password:
    secure: My0T78oC33Rbm7jFRieGUbJpKJEhxGDkiDHOSwXwmmeyPp/PEViWB3eXoD2Gfgb3973iqjYZAvMMElh2m5bK5VwJensf2V3+niSNflrpje71t6kH9qopT2PFrDipCkrkrAp+W4/2iz0dey/y+HKF9acWAv8w35F6ZKhiW8J5LN0x1b02yhsqxLgHeMulQ59K1jm52TvwmraZuv7N0TyjxckO2F4xhzs4yJqz21gs/ctoDoHE76Hp+DQpMj72MdhdFKneQaTTi46clolTsWbMiceLFu8NTJK6co/fOEv3AeGqh2KNzQVLdlGQhfmGKIJwY3dFy95Cd9QDMV+6zB6IzdEro3ggO4Lj64NuUzbNTRI1rO3BMq6K6e7EWwH8pg+j5BO547DhPxpkTNeD8jqcyyqII7lBRdzffh+ROI8UdDL2244gCagcFH3nGCzGFo3vC7wTOiJT9PtYrDj6iYPRuH6TERQVk3/WsW5yKbBj5etKZHKH7UgggfbbicURPAn9OocgpWWBwESu1JoHs7TaI/h1aylw4ASAswVCeexso77FGet/iRUi9AKD2P9RivTLHiOzC0JUweGDufl8riAbAa5zz3ZmcH2eGBUh/An0uxqiilsG9jK4Lg45SdUVlpITDhDNTxmi9HrZEICE7tiHfh1BxLiAzwo+8h4185sBib8=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
