language: python
python:
  - '3.7'
os:
  - linux
env:
  global:
    - TX_BRANCH="master"
install:
  - pip install --upgrade pip setuptools wheel
  - pip install transifex-client sphinx sphinx-intl
  - pip install -r reqs.txt
  - pip install coveralls codecov
  - python setup.py sdist bdist_wheel
  - pip install .
script:
  - cd pruebas
  - coverage run -m unittest
after_success:
  - coveralls --rcfile=.coveragerc
  - codecov
  - cd ..
  - cd docs
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then sh .tx/tx.sh push; sh .tx/tx.sh pull;
    fi
  - cd ..
deploy:
  provider: pypi
  user: julien.malard
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
  password:
    secure: jdaCGWDGhqmLNqDiPVC1kber67m6p4ikEeHJqNIW6K4npcjFDgYOp8CDOxFzkqiOeDJSZiUvOoFCU3xOHEn3wOxI3uA9udOOpjQhDBDfarPVtw8k1c7fH7CmQJNQv4ddZ/bEYPFx/Do8g6XzBUFYiNhbtdq+722mACKC4Kc1eA0peyy6qaRXtRfn9/27kaYOK3Lxj/Bm6NefChaBqzWR5fmePC+k1eiZ8r37oK/TNaZ8PZ7reHOOBsMXNA4b26g7dtZRr665WPqu4pSOP9+gxBKdQ36fvar45x8fueZUdvE3hBVfOrUYebG8IDkT2LJBoJIyfnafN5GXgQ4dsCM2c742HNRECCc5B9wCQc65QVcJ1Fo1Tkozam61s9AW7hIHCsNfwhCH9uw3TAtvnMOqjMMxqfMQxpCYSPWtI0yaIMxt6tHjp7wagl4OzqQwNhJUQWyKwNAxoW/d0oYwoYn4C9LL1o1Qj6l7JrgmdHU1iO3TkNHBbem4Cr6+0nZw2+6d3iE6nJ/wBi3xivwF5sFiuLZY5YHEGn2Y89eh6fZEbL2xOyFibezhEavQcGIk+mACWW2EIVWtvz32ceqffW8h6TIy7GXvCCQ8u1gn21EKDqlCruuKIFk9yMx5TXxe7uSkoE42aeiTxlNASdmu+a6EWhzB8P2hkDiGaPy3buqnTlw=
