language: python
python:
- '3.6'
os:
- linux
env:
  global:
  - TX_BRANCH="master"
install:
- pip install --upgrade pip setuptools wheel
- pip install transifex-client sphinx sphinx-intl
- pip install -r requísitos.txt
- pip install coveralls codecov
- python setup.py sdist bdist_wheel
- pip install tikon --no-index --find-links=./dist
script:
- cd pruebas
- coverage run -m unittest
after_success:
- coveralls --rcfile=.coveragerc
- codecov
- cd ..
- cd docs
- if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then sh .tx/tx.sh push; sh .tx/tx.sh pull;
  fi
- cd ..
deploy:
  provider: pypi
  user: julien.malard
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
  password:
    secure: GDnM9queqsnmOhC2nPsGSS3Y2AUHXChOTxL0sah7fPbTVdXHknCG2Ptr94BRcLT2sCpGFblAD+vJJRSFwPDZFh3zvfP2V8hdxFHypm5jfD4yh3rxUD574NxxDC0X23g9gxeXBat5xPw0tubu27BwooQCxqqWA/L/9l+HiCr5QZ9JsgqE0qha7kNmECGdsuL/suv0vxWdKvYKGEM/mPH6mdsofrnmOQixIQ3Tc4eockJJi0k1SfoZY2crk1LcUSxuiMopskB4fXpu99EtVIB0pH2EWFzZFJTHExsdgn2ujjhGs10DJJbR8TPZuCJRuivj4lHKGaeRCi9KkKcTDSA+f6mP7wDQezNVOCTeIcKuFUEl29JVgUNlVfmcp5ITWy2FBSSH3M5AKpw/HWatYSLFIkPGBkml4Fxx565TqMqYrZ5PCFye28AHP74VFwB2fsbRAQp2zP65adnd39cWZhRGe7m1kOzbz1/eB0RnfEvJEklGyWfweS8c+/cabsN4kvt+RnWhkFhpUWlWxKUt2Z+NeGlXeVrEeInigZF9YBnsDcmjzONkiK2OLbYvWLJdEhGYYKRJSqbPd5jKerzKyrYOVRGjWOV3AA7JpwbvEdZoOyeSkkpF7ep+fVjbswc90w/4UctNrNzG3jyEm2BP1fHteGtySy2B6EtbaeAqjWvYi4M=
